#!/bin/bash

# =============================================================================
# Sub2API One-Click Production Deploy Script
# =============================================================================
# 生成随机密码和密钥，创建 .env 文件，启动 Docker Compose
#
# 使用方法：
#   ./deploy-production.sh
#
# 功能：
#   1. 生成所有必需的随机密码和密钥
#   2. 创建 .env 文件（不会覆盖现有的）
#   3. 启动 docker-compose（带 docker-compose.yml）
#   4. 显示访问信息和关键凭证
# =============================================================================

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 脚本配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="${SCRIPT_DIR}/deploy"
ENV_FILE="${DEPLOY_DIR}/.env"
DOCKER_COMPOSE_FILE="${DEPLOY_DIR}/docker-compose.yml"

# 检查依赖
check_dependencies() {
    echo -e "${BLUE}检查依赖...${NC}"

    if ! command -v docker &> /dev/null; then
        echo -e "${RED}❌ Docker 未安装${NC}"
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        echo -e "${RED}❌ Docker Compose 未安装${NC}"
        exit 1
    fi

    if [ ! -f "$DOCKER_COMPOSE_FILE" ]; then
        echo -e "${RED}❌ 找不到 docker-compose.yml${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ 所有依赖已安装${NC}"
}

# 生成随机密码
generate_password() {
    local length=${1:-32}
    openssl rand -hex $((length / 2))
}

# 生成随机 hex 密钥
generate_hex_key() {
    local length=${1:-32}
    openssl rand -hex $((length / 2))
}

# 创建 .env 文件
create_env_file() {
    echo -e "${BLUE}生成环境变量文件...${NC}"

    if [ -f "$ENV_FILE" ]; then
        echo -e "${YELLOW}⚠ $ENV_FILE 已存在，跳过创建${NC}"
        echo -e "${YELLOW}如需重新生成，请删除 .env 文件后重试${NC}"
        return
    fi

    # 生成所有密码和密钥
    POSTGRES_PASSWORD=$(generate_password 32)
    REDIS_PASSWORD=$(generate_password 32)
    ADMIN_PASSWORD=$(generate_password 16)
    JWT_SECRET=$(generate_hex_key 64)
    TOTP_ENCRYPTION_KEY=$(generate_hex_key 64)

    # 创建 .env 文件
    cat > "$ENV_FILE" << EOF
# =============================================================================
# Sub2API Production Deployment - Generated by deploy-production.sh
# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# =============================================================================

# =============================================================================
# Docker Image Configuration
# =============================================================================
# SUB2API_IMAGE: Sub2API application image
# 镜像从源代码自动构建，无需手动拉取
SUB2API_IMAGE=46.38.157.108:80/sub2api:latest

# =============================================================================
# Server Configuration
# =============================================================================
BIND_HOST=0.0.0.0
SERVER_PORT=8080
SERVER_MODE=release
RUN_MODE=standard

# =============================================================================
# Database Configuration (PostgreSQL)
# =============================================================================
POSTGRES_USER=sub2api
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=sub2api

# =============================================================================
# Redis Configuration
# =============================================================================
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_DB=0

# =============================================================================
# Admin Account (auto-created on first run)
# =============================================================================
ADMIN_EMAIL=admin@sub2api.local
ADMIN_PASSWORD=$ADMIN_PASSWORD

# =============================================================================
# JWT Configuration
# IMPORTANT: 固定值用于保证容器重启后 JWT 仍然有效
# =============================================================================
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_HOUR=24

# =============================================================================
# TOTP Configuration (2FA)
# IMPORTANT: 固定值用于保证容器重启后 TOTP 仍然有效
# =============================================================================
TOTP_ENCRYPTION_KEY=$TOTP_ENCRYPTION_KEY

# =============================================================================
# Timezone Configuration
# =============================================================================
TZ=Asia/Shanghai

# =============================================================================
# Optional: Gemini OAuth Configuration
# =============================================================================
# GEMINI_OAUTH_CLIENT_ID=
# GEMINI_OAUTH_CLIENT_SECRET=
# GEMINI_OAUTH_SCOPES=
# GEMINI_CLI_OAUTH_CLIENT_SECRET=

# =============================================================================
# Optional: Antigravity OAuth Configuration
# =============================================================================
# ANTIGRAVITY_OAUTH_CLIENT_SECRET=
# ANTIGRAVITY_USER_AGENT_VERSION=

# =============================================================================
# Optional: Security Configuration
# =============================================================================
SECURITY_URL_ALLOWLIST_ENABLED=false
SECURITY_URL_ALLOWLIST_ALLOW_INSECURE_HTTP=false
SECURITY_URL_ALLOWLIST_ALLOW_PRIVATE_HOSTS=false

# =============================================================================
# Optional: Update Proxy Configuration
# =============================================================================
# UPDATE_PROXY_URL=http://proxy-host:port

# =============================================================================
# Optional: Database Performance Tuning
# =============================================================================
DATABASE_MAX_OPEN_CONNS=50
DATABASE_MAX_IDLE_CONNS=10
DATABASE_CONN_MAX_LIFETIME_MINUTES=30
DATABASE_CONN_MAX_IDLE_TIME_MINUTES=5

# =============================================================================
# Optional: Redis Performance Tuning
# =============================================================================
REDIS_POOL_SIZE=1024
REDIS_MIN_IDLE_CONNS=10

# =============================================================================
# Optional: Image Generation Configuration
# =============================================================================
GATEWAY_OPENAI_HTTP2_ENABLED=true
GATEWAY_OPENAI_HTTP2_ALLOW_PROXY_FALLBACK_TO_HTTP1=true
GATEWAY_IMAGE_CONCURRENCY_ENABLED=false
EOF

    # 输出生成的凭证信息
    echo -e "${GREEN}✓ .env 文件已生成${NC}"
    echo ""
    echo -e "${YELLOW}=== 重要凭证信息 ===${NC}"
    echo -e "PostgreSQL 密码:  ${RED}$POSTGRES_PASSWORD${NC}"
    echo -e "Redis 密码:       ${RED}$REDIS_PASSWORD${NC}"
    echo -e "管理员密码:       ${RED}$ADMIN_PASSWORD${NC}"
    echo -e "JWT 密钥:         ${RED}$JWT_SECRET${NC}"
    echo -e "TOTP 加密密钥:    ${RED}$TOTP_ENCRYPTION_KEY${NC}"
    echo ""
    echo -e "${YELLOW}⚠ 请妥善保管上述凭证，特别是密码和密钥${NC}"
    echo -e "${YELLOW}⚠ 建议将 .env 文件备份到安全的位置${NC}"
    echo ""
}

# 构建 Docker 镜像
build_docker_image() {
    echo -e "${BLUE}从源代码构建 Docker 镜像...${NC}"
    echo ""

    cd "$SCRIPT_DIR"

    # 获取版本号和提交哈希
    VERSION=$(cat backend/cmd/server/VERSION | tr -d '\n' 2>/dev/null || echo "latest")
    COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "local")
    IMAGE_TAG="46.38.157.108:80/sub2api:v${VERSION}-${COMMIT}"
    IMAGE_LATEST="46.38.157.108:80/sub2api:latest"

    echo -e "${YELLOW}镜像标签:${NC}"
    echo -e "  版本: ${IMAGE_TAG}"
    echo -e "  最新: ${IMAGE_LATEST}"
    echo ""

    echo -e "${BLUE}执行 docker build...${NC}"
    if docker build \
        -t "$IMAGE_TAG" \
        -t "$IMAGE_LATEST" \
        -f Dockerfile \
        . ; then
        echo -e "${GREEN}✓ 镜像构建成功${NC}"
        echo -e "  ${IMAGE_TAG}"
        echo -e "  ${IMAGE_LATEST}"
        echo ""
        return 0
    else
        echo -e "${RED}❌ 镜像构建失败${NC}"
        exit 1
    fi
}

# 启动 Docker Compose
start_docker_compose() {
    echo -e "${BLUE}启动 Docker Compose 服务...${NC}"
    echo ""

    cd "$DEPLOY_DIR"

    # 检查 .env 文件是否存在
    if [ ! -f "$ENV_FILE" ]; then
        echo -e "${RED}❌ .env 文件不存在${NC}"
        exit 1
    fi

    # 启动服务
    if command -v docker-compose &> /dev/null; then
        docker-compose up -d
    else
        docker compose up -d
    fi

    echo -e "${GREEN}✓ Docker Compose 服务已启动${NC}"
}

# 等待服务就绪
wait_for_services() {
    echo -e "${BLUE}等待服务启动...${NC}"

    local max_attempts=30
    local attempt=0

    while [ $attempt -lt $max_attempts ]; do
        if docker exec sub2api wget -q -T 5 -O /dev/null http://localhost:8080/health 2>/dev/null; then
            echo -e "${GREEN}✓ Sub2API 服务已就绪${NC}"
            return 0
        fi

        attempt=$((attempt + 1))
        echo -e "${YELLOW}等待中... ($attempt/$max_attempts)${NC}"
        sleep 2
    done

    echo -e "${YELLOW}⚠ 服务启动超时，但容器已运行${NC}"
}

# 显示启动信息
show_info() {
    echo ""
    echo -e "${GREEN}================================${NC}"
    echo -e "${GREEN}✓ Sub2API 已成功启动${NC}"
    echo -e "${GREEN}================================${NC}"
    echo ""
    echo -e "${BLUE}访问信息：${NC}"
    echo -e "  URL: ${GREEN}http://localhost:8080${NC}"
    echo -e "  管理员邮箱: admin@sub2api.local"
    echo -e "  管理员密码: 已保存在 .env 文件中的 ADMIN_PASSWORD"
    echo ""
    echo -e "${BLUE}常用命令：${NC}"
    echo -e "  查看日志:   ${YELLOW}docker-compose logs -f sub2api${NC}"
    echo -e "  停止服务:   ${YELLOW}docker-compose down${NC}"
    echo -e "  重启服务:   ${YELLOW}docker-compose restart${NC}"
    echo -e "  查看状态:   ${YELLOW}docker-compose ps${NC}"
    echo ""
    echo -e "${BLUE}文件位置：${NC}"
    echo -e "  环境变量:   ${YELLOW}$ENV_FILE${NC}"
    echo -e "  数据目录:   ${YELLOW}$(pwd)/volumes/${NC}"
    echo ""
    echo -e "${YELLOW}注意事项：${NC}"
    echo -e "  • PostgreSQL、Redis 等服务的密码已自动生成在 .env 中"
    echo -e "  • 请备份 .env 文件和数据目录"
    echo -e "  • 如需修改配置，编辑 .env 后执行: docker-compose down && docker-compose up -d"
    echo -e "  • 首次启动需要初始化数据库，请耐心等待"
    echo ""
}

# 主函数
main() {
    echo -e "${BLUE}"
    cat << 'EOF'
╔═══════════════════════════════════════════════════════════════╗
║         Sub2API 生产级一键部署脚本                            ║
║    One-Click Production Deployment Script                    ║
╚═══════════════════════════════════════════════════════════════╝
EOF
    echo -e "${NC}"
    echo ""

    # 执行各个阶段
    check_dependencies
    echo ""
    build_docker_image
    echo ""
    create_env_file
    echo ""
    start_docker_compose
    echo ""
    wait_for_services
    echo ""
    show_info
}

# 错误处理
trap 'echo -e "${RED}❌ 脚本执行出错${NC}"; exit 1' ERR

# 运行主函数
main
